### ISSUE TITLE
USER STORY: Book a table

### ISSUE THREAD

**Issue by Pernilla-Strandberg** [Pernilla-Strandberg/django-restaurant-app#10]
As a guest, I can **select date, time and number of guests for my reservation** so that I can **plan my dining experience in advance and secure a table.**

## Acceptance Criteria
1. A booking page with a booking form
2. Form has input fields or buttons to customize the booking
3. Number of guests, date, time and email field is present and required
4. Fully booked days and/or times are clearly visible and cannot be selected
5. The page looks good in different browsers and sizes
6. Validation messages informs guest about input errors or empty fields
7. Confirmation view loads after submit
8. A confirmation email is sent with booking details and how to cancel/change booking

## Tasks
- [x] Create responsive booking page with a booking form
- [x] Create input fields or buttons for the guest to interact with
- [x] Create a model in Django project for this form
- [x] Create class-based views in Django project
- [x] Create validation rules and messages for all user input
- [x] Implement date and time picker
- [x] Create confirmation view
