### ISSUE TITLE
USER STORY: Newsletter subscription service

### ISSUE THREAD

**Issue by Pernilla-Strandberg** [Pernilla-Strandberg/django-restaurant-app#4]
As a guest, I can **subscribe to newsletters or updates from the restaurant** so that I can **stay informed about new menu items, events, or special promotions.**

## Acceptance Criteria
1. Newsletter subscription input field is present in the footer

## Tasks
- [ ] Create newsletter subscription input field in footer
- [ ] Collect user email in database
- [ ] Implement newsletter service
