### ISSUE TITLE
USER STORY: Reach customer support

### ISSUE THREAD

**Issue by Pernilla-Strandberg** [Pernilla-Strandberg/django-restaurant-app#5]
As a guest, I can **easily reach customer support** so that I can **receive assistance with any inquiries or issues related to my reservation.**

## Acceptance Criteria
1. Contact form is present on the contact page
2. Support phone number is visible on the contact page and/or in footer
3. A link from the booking page leads to the contact page

## Tasks
- [ ] Create contact form on the contact page
- [ ] Display phone number on the contact page and/or in footer
- [ ] Create "Do you need help with your booking?" link that leads to contact page
