### ISSUE TITLE
USER STORY: Get restaurant directions

### ISSUE THREAD

**Issue by Pernilla-Strandberg** [Pernilla-Strandberg/django-restaurant-app#7]
As a guest, I can **access directions or a map to the restaurant** so that I can **easily find the location without any hassle.**

## Acceptance Criteria
1. Map and/or directions to the restaurant is present on a contact page
2. Directions by bus and/or car is described  
3. Address is visible

## Tasks
- [ ] Implement Google map in Contact page
- [ ] Describe directions by bus and/or car
- [x] Add address information
