### ISSUE TITLE
USER STORY: Change or cancel booking

### ISSUE THREAD

**Issue by Pernilla-Strandberg** [Pernilla-Strandberg/django-restaurant-app#8]
As a guest, I can **easily modify the details of my reservation, such as the number of guests or the time** so that I can **adapt to any changes in my plans.**

## Acceptance Criteria
1. A booking can be changed or cancelled by the guest
2. A unique view is present for each guest with two buttons: "Cancel reservation" and "Change reservation".
3. Number of guests, date and time can be edited
4. Fully booked days and/or times are clearly visible and cannot be selected
5. The page looks good in different browsers and sizes
6. Validation messages informs guest about input errors or empty fields
7. Confirmation view loads after cancelling or changing the reservation
8. A confirmation email is sent with new booking details or cancellation confirmation

## Tasks
- [ ] Create function-based views in Django project
- [ ] Create validation rules and messages for all user input
- [ ] Create confirmation views
- [ ] Create confirmation emails
- [ ] Ensure good responsiveness in different browsers and screen sizes
