### ISSUE TITLE
USER STORY: Browse restaurant menu

### ISSUE THREAD

**Issue by Pernilla-Strandberg** [Pernilla-Strandberg/django-restaurant-app#9]
As a guest, I can **browse the restaurant menu online** so that **I can review the available options before deciding to make a reservation.**

## Acceptance Criteria
1. A menu page showing available dishes
2. Each dish has a description of the ingredients
3. Inviting hero image of the restaurant's dishes that gives a strong association to South American cuisine
4. The page looks good in different browsers and sizes

## Tasks
- [ ] Create responsive menu page with hero image
- [ ] Describe each dish simply but informatively with included ingredients
- [ ] Test page in different browsers and sizes
